[package]
name = "chess"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.17"
log = "0.4.28"
reqwest = { version = "0.12.24", features = ["blocking", "json"] }
serde_json = "1.0.145"
serde = { version = "1.0.228", features = ["derive"] }
